BREAKABLES = {}
BREAKABLES['carrot plant'] = {'break type': 'sudden', 'wobble': True, 'weapon required': ['sword', 'dagger', 'plasma', 'axe', 'shovel'], 'animate speed': 50, 'right weapon hit sound': 'rustle', 'hit sound': 'rustle', 'break sound': 'rustle', 'health': 1, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': True, 'items': {'carrot':2}, 'min drop': 1, 'rare items': ['green moth']}
BREAKABLES['potato bush'] = {'break type': 'sudden', 'wobble': True, 'weapon required': ['sword', 'plasma', 'axe', 'shovel'], 'animate speed': 50, 'right weapon hit sound': 'rustle', 'hit sound': 'rustle', 'break sound': 'rustle', 'health': 2, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': True, 'items': {'potato':3}, 'min drop': 1, 'rare items': ['red crystal', 'rabbit', 'green moth', 'snake', 'garden lizard']}
BREAKABLES['hedge'] = {'break type': 'sudden', 'wobble': True, 'weapon required': ['sword', 'plasma', 'axe', 'shovel'], 'animate speed': 50, 'right weapon hit sound': 'rustle', 'hit sound': 'rustle', 'break sound': 'rustle', 'health': 3, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': True, 'items': {'cut green wood':1}, 'rare items': ['red crystal', 'green moth', 'snake', 'garden lizard', 'green crystal']}
BREAKABLES['rose bush'] = {'break type': 'sudden', 'wobble': True, 'weapon required': ['sword', 'plasma', 'axe', 'shovel'], 'animate speed': 50, 'right weapon hit sound': 'rustle', 'hit sound': 'rustle', 'break sound': 'rustle', 'health': 3, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': True, 'items': {'yellow rose':5}, 'min drop': 1, 'rare items': ['yellow crystal', 'green moth', 'garden lizard', 'green crystal']}
BREAKABLES['fern'] = {'break type': 'sudden', 'wobble': True, 'weapon required': ['sword', 'plasma', 'axe', 'shovel'], 'animate speed': 50, 'right weapon hit sound': 'rustle', 'hit sound': 'rustle', 'break sound': 'rustle', 'health': 3, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': True, 'items': {'cut green wood':1}, 'rare items': ['blue crystal', 'green moth', 'snake', 'garden lizard', 'green crystal']}
BREAKABLES['iron vein'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 4, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'iron ore':4}, 'rare items': [None]}
BREAKABLES['gold vein'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 4, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'gold ore':4}, 'rare items': [None]}
BREAKABLES['silver vein'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 4, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'silver ore':4}, 'rare items': [None]}
BREAKABLES['aluminum vein'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 4, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'aluminum ore':4}, 'rare items': [None]}
BREAKABLES['tin vein'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 4, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'tin ore':4}, 'rare items': [None]}
BREAKABLES['copper vein'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 4, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'copper ore':4}, 'rare items': [None]}
BREAKABLES['breakable rock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 4, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'ordinary rock':9}, 'rare items': ['flint stone']}
BREAKABLES['breakable wall'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 4, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'brick':6}, 'rare items': [None]}
BREAKABLES['empty turtle shell'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['mace', 'pickaxe', 'axe'], 'animate speed': 50, 'right weapon hit sound': 'rock_hit', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 2, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': True, 'items': {'turtle shell plate':12}, 'min drop': 4, 'rare items': ['bluefish']}
BREAKABLES['dead tree'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['axe', 'plasma'], 'animate speed': 70, 'right weapon hit sound': 'rock_hit', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'cut dry wood':12}, 'rare items': ['dead brown bird']}
BREAKABLES['palm tree'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['axe', 'plasma'], 'animate speed': 70, 'right weapon hit sound': 'rock_hit', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'cut green wood':12, 'palm leaf': 10, 'coconut': 6}, 'rare items': ['dead brown bird']}
BREAKABLES['green tree'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['axe', 'plasma'], 'animate speed': 70, 'right weapon hit sound': 'rock_hit', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'cut green wood':12}, 'rare items': ['dead brown bird']}
BREAKABLES['pine tree'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['axe', 'plasma'], 'animate speed': 70, 'right weapon hit sound': 'rock_hit', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'cut green wood':12, 'pine branch': 10}, 'rare items': ['dead brown bird']}
BREAKABLES['crack'] = {} # used to load the images for all the ore vein blocks below
BREAKABLES['stoneblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'ordinary rock':10}, 'rare items': ['flint stone']}
BREAKABLES['coalblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'coal':6}, 'rare items': ['clay']}
BREAKABLES['ironblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'iron ore':6}, 'rare items': [None]}
BREAKABLES['goldblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'gold ore':6}, 'rare items': [None]}
BREAKABLES['tinblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'tin ore':6}, 'rare items': [None]}
BREAKABLES['silverblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'silver ore':6}, 'rare items': [None]}
BREAKABLES['copperblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'copper ore':6}, 'rare items': [None]}
BREAKABLES['aluminumblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'aluminum ore':6}, 'rare items': [None]}
BREAKABLES['zincblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'zinc ore':6}, 'rare items': [None]}
BREAKABLES['leadblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'lead ore':6}, 'rare items': [None]}
BREAKABLES['diamondblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'diamond':5}, 'rare items': [None]}
BREAKABLES['whitecrystalblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'white crystal':1}, 'rare items': [None]}
BREAKABLES['blackcrystalblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'black crystal':1}, 'rare items': [None]}
BREAKABLES['yellowcrystalblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'yellow crystal':1}, 'rare items': [None]}
BREAKABLES['greencrystalblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'green crystal':1}, 'rare items': [None]}
BREAKABLES['redcrystalblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'red crystal':1}, 'rare items': [None]}
BREAKABLES['bluecrystalblock'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe'], 'animate speed': 50, 'right weapon hit sound': 'pickaxe', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 5, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'blue crystal':1}, 'rare items': [None]}
BREAKABLES['dirt'] = {'break type': 'gradual', 'wobble': False, 'weapon required': ['pickaxe', 'shovel'], 'animate speed': 50, 'right weapon hit sound': 'rock_hit', 'hit sound': 'rock_hit', 'break sound': 'rocks', 'health': 2, 'damage': 0, 'knockback': 0, 'protected': False, 'random drop number': False, 'items': {'blue crystal':0}, 'rare items': ['clay']}
BLOCK_DICT = {0: 'stoneblock', 1: 'coalblock', 2: 'ironblock', 3: 'goldblock', 4: 'tinblock', 5: 'silverblock', 6: 'copperblock', 7: 'aluminumblock', 8: 'zincblock', 9: 'leadblock', 10: 'diamondblock', 11: 'whitecrystalblock', 12: 'blackcrystalblock', 13: 'yellowcrystalblock', 14: 'greencrystalblock', 15: 'redcrystalblock', 16: 'bluecrystalblock', 17: 'dirt'}
BLOCK_LIST = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
BLOCK_PROB = [0.86, 0.01, 0.01, 0.005, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.005, 0.005, 0.005, 0.01, 0.01, 0.01, 0.01, 0]
#for item in BREAKABLES:
#    if 'block' in item:
#        BLOCK_LIST.append(item)

#BLOCK_PROB = [0.5, 0.25, 0.2, 0.05]


VEIN_LIST = []
for item in BREAKABLES:
    if 'vein' in item:
        VEIN_LIST.append(item)
    if 'rock' in item:
        VEIN_LIST.append(item)

TREE_LIST = []
for item in BREAKABLES:
    if 'tree' in item:
        if 'palm tree' not in item:
            TREE_LIST.append(item)

PLANT_LIST = []
for item in BREAKABLES:
    if 'plant' in item:
        PLANT_LIST.append(item)
    if 'bush' in item:
        PLANT_LIST.append(item)

BEACH_PLANT_LIST = ['palm tree']


