QUESTS = {}
QUESTS['A fish for Loella'] = {'accepted': False, 'completed': False, 'rewarded': False, 'inventory check': False,
                               'description': 'Catch a goldfish for Loella\'s fish tank in the town of Dewcastle.',
                               'accept text': ['Oh, thank you so much! I\'m so excited!'],
                               'deny text': ['Oh... ok. I hope my daddy will get home soon to help me.'],
                               'completed text': ['I love my new fish!'],
                               'waiting text': ['Have you found a fish for me yet? I hope you find one soon. I\'m so excited. Please hurry.'],
                               'reward': {'weapons': [None], 'hats': [None], 'hair': [None], 'tops': [None], 'bottoms': [None], 'shoes': [None], 'gloves': [None],
                  'items': ['potion of major healing'], 'gold': 0},
                               'reward text': ['Thank you so much for the fish. Please take this healing potion as a token of my appreciation.'],
                               'next quest': 'A friend for Loella',
                               'next dialogue': 'LOELLA_DLG2'}

QUESTS['A friend for Loella'] = {'accepted': False, 'completed': False, 'rewarded': False, 'inventory check': False,
                               'description': 'Loella needs help finding a friend in the town of Dewcastle.',
                               'accept text': ['Oh, thank you so much! I\'m so excited to meet my new friend!'],
                               'deny text': ['Oh... ok. I guess I\'ll have to go out and make friends like a normal kid.'],
                               'completed text': ['I\'m really enjoying playing with Kimmy!'],
                               'waiting text': ['Have you found a friend for me yet? I hope you find one soon. I\'m so excited. Please hurry.'],
                               'reward': {'weapons': [None], 'hats': [None], 'hair': [None], 'tops': [None], 'bottoms': [None], 'shoes': [None], 'gloves': [None],
                  'items': ['potion of major stamina'], 'gold': 0},
                               'reward text': ['Thank you so much for introducing me to Kimmy! Please take this stamina potion as a token of my appreciation.'],
                               'next quest': None,
                               'next dialogue': None}

QUESTS['A mace for Steve'] = {'accepted': False, 'completed': False, 'rewarded': False, 'inventory check': True, 'needed item': 'mace',
                               'description': 'Steve is a slacker and lost his mace. He needs help finding a new one in the town of Dewcastle.',
                               'accept text': ['Oh, thank you so much! You\'re a life saver.'],
                               'deny text': ['Thanks okay. I can see you\'re busy.'],
                               'completed text': ['This new mace is awesome. You really saved my neck.'],
                               'waiting text': ['Have you found that mace for me yet? The captain will have my head for this. Please hurry.'],
                               'has item text': ['I see you brought me a mace. May I have it?YN'],
                               'refuse to give text': ['That\'s not at all what we agreed to. How rude.'],
                               'reward': {'weapons': [None], 'hats': [None], 'hair': [None], 'tops': [None], 'bottoms': [None], 'shoes': [None], 'gloves': [None],
                  'items': ['baked potato', 'cheese wedge'], 'gold': 12},
                               'reward text': ['Thanks so much. Sorry, I don\'t have much to reward you with, but here\'s my lunch and what\'s left of yesterday\'s wages.'],
                               'next quest': None,
                               'next dialogue': 'STEVE_DLG2'}

QUESTS['Ant eggs for Tamolin'] = {'accepted': False, 'completed': False, 'rewarded': False, 'inventory check': True, 'needed item': 'giant ant eggs',
                               'description': 'Tamolin of Dewcastle wants you to find giant ant eggs so he can create powerful new potions. Search the ant tunnels to the south and see if you can find any eggs.',
                               'accept text': ['Oh, thank you. I would have gone myself, but I\'d have no one to watch the shop for me.'],
                               'deny text': ['Not up to it huh? Perhaps I can find someone else who is brave enough.'],
                               'completed text': ['These eggs are beautiful. They are much larger than I expected.'],
                               'waiting text': ['Any luck finding those ant eggs for me?'],
                               'has item text': ['Wonderful! I see you found some giant ant eggs. May I have them?YN'],
                               'refuse to give text': ['Oh, so you want them for yourself huh? Ok, good luck figuring out what to do with them.'],
                               'reward': {'weapons': [None], 'hats': [None], 'hair': [None], 'tops': [None], 'bottoms': [None], 'shoes': [None], 'gloves': [None],
                  'items': [None], 'gold': 2000},
                               'reward text': ['Amazing! I can tell you are a brave adventurer.'],
                               'next quest': None,
                               'next dialogue': 'TAMOLIN_DLG2'}

QUESTS['Clay for Tamolin'] = {'accepted': False, 'completed': False, 'rewarded': False, 'inventory check': True, 'needed item': 'giant ant eggs',
                               'description': 'Tamolin of Dewcastle wants you to eggs.',
                               'accept text': ['Oh, thank you. I would have gone myself, but I\'d have no one to watch the shop for me.'],
                               'deny text': ['Not up to it huh? Perhaps I can find someone else who is brave enough.'],
                               'completed text': ['These eggs are beautiful. They are much larger than I expected.'],
                               'waiting text': ['Any luck finding those ant eggs for me?'],
                               'has item text': ['Wonderful! I see you found some giant ant eggs. May I have them?YN'],
                               'refuse to give text': ['Oh, so you want them for yourself huh? Ok, good luck figuring out what to do with them.'],
                               'reward': {'weapons': [None], 'hats': [None], 'hair': [None], 'tops': [None], 'bottoms': [None], 'shoes': [None], 'gloves': [None],
                  'items': [None], 'gold': 2000},
                               'reward text': ['Amazing! I can tell you are a brave adventurer.'],
                               'next quest': None,
                               'next dialogue': 'TAMOLIN_DLG2'}

QUESTS['Fuel for Felius'] = {'accepted': False, 'completed': False, 'rewarded': False, 'inventory check': True, 'needed item': 'airship fuel', 'action': 'companion',
                               'description': 'Find some fuel for Felius\' airship, so he can go back home.',
                               'accept text': ['Oh, thank you so much! Please take as many of those empty barrels by my house as you can carry. You\'ll need them to bring the fuel back in.', 'Good luck my friend!'],
                               'deny text': ['Oh, I hope you change your mind. I\'m not sure how much longer I can survive out here.'],
                               'completed text': ['This is perfect! You really saved my life. You won\'t regret this!'],
                               'waiting text': ['Any luck finding airship fuel? I could probably make some if I had an alchemy lab.', 'An alchemist friend of mine made the fuel, using oil and alcohol.'],
                               'has item text': ['Wonderful! You found the fuel. May I have it?YN'],
                               'refuse to give text': ['Oh, well that\'s cruel of you to bring it all this way just to taunt me.'],
                               'reward': {'weapons': [None], 'hats': [None], 'hair': [None], 'tops': [None], 'bottoms': [None], 'shoes': [None], 'gloves': [None],
                  'items': [None], 'gold': 0},
                               'reward text': ['Thank you so much! Now I can be with my family again. I don\'t have anything to offer except for my airship. I think I\'ve done enough exploring for one lifetime. Accompany me home and the key is yours.'],
                               'next quest': 'Take Felius Home',
                               'next dialogue': 'FELIUS_DLG2'}

QUESTS['Take Felius Home'] = {'accepted': False, 'completed': False, 'rewarded': False, 'inventory check': False, 'autoexcept': True,
                               'description': 'Escort Felius back to his home in Norwald.',
                               'completed text': ['I\'m so happy to be home.'],
                               'waiting text': ['I hope it doesn\'t take us too much longer to get home.', 'It\'s a long way home to Norwald. I\'m glad to have a warrior like you accompanying me.', 'I\'ll fight for you so long as we are together friend.'],
                               'reward': {'weapons': [None], 'hats': [None], 'hair': [None], 'tops': [None], 'bottoms': [None], 'shoes': [None], 'gloves': [None],
                  'items': ['airship key'], 'gold': 0},
                               'reward text': ['Thank you so much! I\'m so happy to be with my family again. Here\'s the key to my airship. Please take good care of her.'],
                               'next quest': None,
                               'next dialogue': 'FELIUS_DLG2'}